### ISSUE TITLE
BongaCams not records

### ISSUE THREAD

**Issue by nikop525** [lossless1024/StreaMonitor#10]
Controller.py status

BongaCams  | True    | Not running 

3 days worked then stopped, ip changed.

**Comment by DerBunteBall** [comment]
Hi,

I thinkt this were fixed today.

Check the todays commit a96cfc57996d7bbe32822b23fab246ac781a6dc4 and try again.

Also rerun pip in your pyenv to have ffmpy installed.

Best Regards
