### ISSUE TITLE
SCVR not working anymore

### ISSUE THREAD

**Issue by kingdan78** [lossless1024/StreaMonitor#105]
looks like SC changed their API and the recordings are now erroring. I saw another software that has been able to fix it, but this software is paid and not as stable as this one.
Any possibility to fix this?

**Comment by mK33y** [comment]
#106

**Comment by thenab0303** [comment]
Appreciate the error fix but is there a way to fix it that preserves the ability to record private shows, brb screens, exclusives like it used to? Or did their update completely ruin that?

**Comment by mK33y** [comment]
this script had never the ability to record private shows or anything you mentioned.

**Comment by kingdan78** [comment]
The private show was a glitch on Stripchat's side.... you could also spy for free live in your VR headset..... It seems like their update fixed that glitch unfortunately :(

**Comment by thenab0303** [comment]
Well that's a shame, was nice while it lasted I guess.

**Comment by xAstroBoy** [comment]
#111  i fixed it here. enjoy!
