### ISSUE TITLE
Bad status nonexistent user on CAM4 

### ISSUE THREAD

**Issue by manitou153** [lossless1024/StreaMonitor#109]
With severals models in CAM4, when I check their status, nonexistent user is returned while these models really exist.
Any idea ?
I run Streamonitor in a docker container, this problem does not seem to be present when I run it directly with the python command on my linux machine 
Thank you !

**Comment by lossless1024** [comment]
Did you rebuild the image recently?

**Comment by manitou153** [comment]
@lossless1024 yes I did.
This issue is related to the location of the VPN I am using. In fact, some models restrict the geographic scope of access. I just configured my VPN with a region accepted by the model and I no longer have the issue.
With the wrong location, curl returned 403 forbidden and streamonitor indicates in this case non existentuser

**Comment by lossless1024** [comment]
I see. I'll maybe add a better status message for this

**Comment by manitou153** [comment]
I also modified the docker-compose manifest to automatically add a container including advanced management of major VPN providers. Streamonitor therefore does not work if the VPN is not launched or if it is unhealthy

**Comment by lossless1024** [comment]
Just for curiosity, what are you using for this?

**Comment by manitou153** [comment]
The Gluetun solution
