### ISSUE TITLE
Amateur TV new encryption. 

### ISSUE THREAD

**Issue by webmastermario** [lossless1024/StreaMonitor#116]
Hello,

recently since 2 days, Amateur.tv has made changes and when i record a stream with ffmpeg i receive this:

 Failed to seek for auxiliary info, will only parse senc atoms for encryption info
    Last message repeated 5 times

Anyone who can help correct this issue?

Thanks

**Comment by Ro-Den** [comment]
They are switching to SAMPLE-AES Widevine DRM protection. Nobody would help it here. So, good luck "correcting" the issue yourself );

**Comment by eldepor** [comment]
Been recording it perfectly since last few days that I get these corrupted or encrypted recordings:
@lossless1024 thanks 
![image](https://github.com/lossless1024/StreaMonitor/assets/19383172/08cef513-f4a2-483f-b0c6-a20ab3613fc7)

**Comment by Ro-Den** [comment]
@eldepor So, decrypt them ); What's the problem? They don't use Widevine anymore, so chances are the key is being sent unencrypted.

**Comment by eldepor** [comment]
> @eldepor So, decrypt them ); What's the problem? They don't use Widevine anymore, so chances are the key is being sent unencrypted.

Who are you? I'm asking for the dev for a fix in the py code for this site so it can record again. Shut up.
