### ISSUE TITLE
Stripchat recordings repeatedly restarting

### ISSUE THREAD

**Issue by yayayeet69** [lossless1024/StreaMonitor#126]
As the title says, stripchat recordings are repeatedly restarting, creating many ~1MB files rather than one continuous video.

**Comment by Acenl12** [comment]
Same issue here. I recorded a stream on SC for 30 minutes and now have 209 files in a directory

**Comment by Ryner95** [comment]
I just formatted my PC and the same thing happened to me because of the ffmpeg that I downloaded. In the end I managed to fix it by downloading the following one [https://www.mediafire.com/file/i8b11wregtv0p22/FFMPEG.rar/file](url)

**Comment by xAstroBoy** [comment]
Is still happening for me

**Comment by khaoniaomamuang** [comment]
Hey I fixed it by using FFmpeg binary "full" version found here https://www.gyan.dev/ffmpeg/builds/

**Comment by Ryner95** [comment]
> Hey I _mostly_ fixed it by using FFmpeg binary "full" version found here https://www.gyan.dev/ffmpeg/builds/

With which build of all?

**Comment by SomeQne** [comment]
Seems to work ok with the release build version 6.0 of FFmpeg (https://www.gyan.dev/ffmpeg/builds/, I tested the full build but I don't think it matters).

**Comment by lossless1024** [comment]
Duplicate. Also thanks for the FFMpeg tip
