### ISSUE TITLE
Amateur TV not recording properly

### ISSUE THREAD

**Issue by eldepor** [lossless1024/StreaMonitor#146]
Hello, I think they implemented a token or something because recorded files are encrypted since few weeks ago and all I see is this (attached img). Can you check it?

Thanks.

![image](https://github.com/lossless1024/StreaMonitor/assets/19383172/e3dc9db8-5967-489e-94ea-5bb666966e00)

**Comment by Ro-Den** [comment]
> Can you check it?

Check what?

Duplication of https://github.com/lossless1024/StreaMonitor/issues/116

**Comment by eldepor** [comment]
> > Can you check it?
> 
> Check what?
> 
> Duplication of #116

The code? So it can properly record again from this site?

**Comment by Ro-Den** [comment]
@eldepor The code is OK. It's recording properly ); Just get the encryption key and decrypt );

**Comment by eldepor** [comment]
> @eldepor The code is OK. It's recording properly ); Just get the encryption key and decrypt );

That's what I'm asking the DEV to implement in the code if possible.

**Comment by Ro-Den** [comment]
There's plenty of information on how to get the key, no need to beg the DEV waste his time.

P.S.: And by the way, they encrypt content for a reason!

**Comment by eldepor** [comment]
> There's plenty of information on how to get the key, no need to beg the DEV waste his time.
> 
> P.S.: And by the way, they encrypt content for a reason!

Are you the dev? Then shut the F up because that's not your business.

PS: You are reported spammern!

**Comment by Ro-Den** [comment]
@eldepor What's your problem? Loosing lots of money 'cause can't sell  those videos no more?

Dev is an idiot to help people like you for free.

**Comment by eldepor** [comment]
Please we need a fix.

**Comment by eldepor** [comment]
If you check the code of the site there's a key.bin file along with the m3u8 and fmp4 url, I have no idea of how to use that.

**Comment by eldepor** [comment]
> If you check the code of the site there's a key.bin file along with the m3u8 and fmp4 url, I have no idea of how to use that.

Anyone checked if this is useful?

**Comment by eldepor** [comment]
In the json you can find

"fmp4":"https://live-fmp4-edge.a0s.net/play/live.mp4?token=eyJhbGciO......."
"fmp4-hls":"https://live-hls-edge.a0s.net/play/master.m3u8?token=eyJhbGciO....."}

And inside the m3u8, the key: 
https://live-fmp4-edge.a0s.net/play/key.bin?token=eyJhbGciOi.............

Cant this be used in the bot to decrypt?

**Comment by eldepor** [comment]
OK after seeing no one is interested in a workaround for ATV I decided to modify the bot myself, with success, adding the hability to download and decrypt the stream with m3u8dl_re as a new dowloader instead of ffmpeg, and getting the widevine keys with other tools. Obviously I won't upload it anywhere since no one cares, but I'm gonna enjoy it a lot ;) . Cheers!

**Comment by eldepor** [comment]
OK after seeing no one is interested in a workaround for ATV I decided to modify the bot myself, with success. If the dev or anyone else is interested in implementing it or make a fork, just let me know

**Comment by 77Mike7** [comment]
I would be very grateful if you could share the solution.

**Comment by reallyquiet00** [comment]
Here there is another one that would be very grateful if you could share the solution (or allow access to your repo).

**Comment by RJamieKelly** [comment]
could you show me your solution or allow access to the repo? thanks

**Comment by epuertas** [comment]
Could you please invite me to the private repo too? I have been trying to find out how to decrypt the streams, but I was not able to do it. It would be very helpful to see how you do it

**Comment by Endless-Zone** [comment]
Could you show me or send me an invite as well? This has been driving me crazy for a while haha

**Comment by respi44** [comment]
Please could you send me an invitation too?

**Comment by missproject** [comment]
I know its been a while but ... Please may you send me an invitation too ? Id love to find a workaround with this decrypt key :)

**Comment by hardcoreTest** [comment]
@eldepor Please may you send me an invitation too
