### ISSUE TITLE
Sorry, I have a download problem, can anyone help me? Thanks

### ISSUE THREAD

**Issue by boobpussy** [lossless1024/StreaMonitor#149]
I don't understand python
According to the tutorial, I seem to start the scrip ？But I'm not sure
![image](https://github.com/lossless1024/StreaMonitor/assets/143272032/86709496-a53d-44b7-9308-76fa4625188d)
![image](https://github.com/lossless1024/StreaMonitor/assets/143272032/62b2a4c8-d0c0-4287-bf3f-df0b5f04a9f0)
I started recording.But it keeps reminding me ‘Rate limited’.Is the network too bad?Or is it because I’m using a VPN?
That’s why it didn’t enter the downloading state？making it impossible to record.Can you teach me ? Thank you.
There is another question. I started recording the SC platform anchor script, but it reported an error. How should I deal with it?
![image](https://github.com/lossless1024/StreaMonitor/assets/143272032/ad418cdf-5135-4ea6-8118-4022bf0be898)
Is it because my configuration has not been changed?

**Comment by boobpussy** [comment]
![image](https://github.com/lossless1024/StreaMonitor/assets/143272032/750af18b-e383-4bcb-9f5d-0d63e76b27dc)
The SC script is started, but the status has not changed.

**Comment by boobpussy** [comment]
> 1. Chaturbate doesn't work because the API is protected by Cloudflare since a few weeks. StreaMonitor can't handle this acutally. I also guess it won't be able in future.
> 2. The StripChat Thread just not running. I guess it's possible that it is stopped due to the Exception. I can't tell you what's the reason for this without the other Exception. I guess it's some TLS related stuff.

I'll change the network and I can download it.But the download address I assigned did not take effect, and the downloaded video was very short.I waited for half an hour and it only rained for a minute

**Comment by boobpussy** [comment]
![image](https://github.com/lossless1024/StreaMonitor/assets/143272032/822b2048-112f-4c29-a7d7-2ef8879bbc58)
This is the address after I changed it, but it is actually still in the project download file

**Comment by DerBunteBall** [comment]
This is related to the fact that StripChat uses low latency streaming. See #35, #139.

That's actually not really supported by ffmpeg. You can try to add ```-re``` to the command line. But that's a really dirty workaround.

**Comment by boobpussy** [comment]
> This is related to the fact that StripChat uses low latency streaming. See #35, #139.
> 
> That's actually not really supported by ffmpeg. You can try to add `-re` to the command line. But that's a really dirty workaround.

![image](https://github.com/lossless1024/StreaMonitor/assets/143272032/b6f34948-71d5-4aa3-80dc-389c07ebd6d9)
-re ？？ is that so .but no effect

**Comment by DerBunteBall** [comment]
You need to patch your code. ```-re``` is a ffmpeg option.

See #135

Also see ```./streamonitor/downloaders/ffmpeg.py``` staring at line 10.

Keep in mind that this will affect all sites because there is actually no way to give downlaoder related options within a site module.
