### ISSUE TITLE
No MFC streams getting detected at all (since yesterday)

### ISSUE THREAD

**Issue by ashamefuldog** [lossless1024/StreaMonitor#158]
To be clear, I realize StreaMonitor can sometimes take a few minutes to detect a running stream and am fine with that, but this has been going on all afternoon so I'm starting to wonder if something's up. Everything's just showing up as "no stream," I even tried adding a bunch of random channels I can see active just to make sure it isn't just a problem with a handful of specific ones, but nope, nothing registers. Wonder if something changed on MFC's end. Or is this somehow just a me problem? Anyone else having this issue?

**Comment by LooieBloo** [comment]
I am seeing the same thing as well.  I am wondering if they changed something that messes with the way its identifying if a stream is active.  I can still get the m3u8 URL from browser tools and stream and save that right from ffmpeg, and that URL format does not look to have changed.  Something changed with https://www.myfreecams.com/php/tracking.php?

**Comment by ashamefuldog** [comment]
Yeah, still nothin' today, either.

**Comment by LooieBloo** [comment]
I am far from any good with python, but it looks to me as if its looking at the content of https://share.myfreecams.com for a class=campreview-link.  I do not see a class with that name, so I am assuming its been changed/removed.  The really not being any good with python is why I cannot figure out what values its looking for from that.  Now I could be completely off the mark here, so I hope that someone with some real knowledge can get a look at this.

**Comment by MartinR577** [comment]
I'm still having this issue. has anyone found a solution?  I tried the ThrowAwaUser5678/StreaMonitor fork but it didn't make a difference. i may not have done it right, It may have pulled the wrong version when i ran docker compose

**Comment by ashamefuldog** [comment]
> I'm still having this issue. has anyone found a solution? I tried the ThrowAwaUser5678/StreaMonitor fork but it didn't make a difference. i may not have done it right, It may have pulled the wrong version when i ran docker compose

The fork is working fine for me, though it took me a sec to figure out how to use it correctly because I've got no idea what I'm doing and am just flying by the seat of my pants, so keep that in mind when I try to explain this, but: you can't just download the suggested fork and use it outta the box yet. Go [here](https://github.com/lossless1024/StreaMonitor/pull/159/commits/3012d20c7a47d865cd17f1858a7943bb957e3c07), and look for lines that are highlighted in red (two near the top, one near the bottom) - these red lines are what's currently in your myfreecams.py file (located at (whatever)\StreaMonitor-master\streamonitor\sites) that need to be changed to make it work, and the green lines immediately underneath those are Throwaway's suggested fixes. So you can't just download the whole fork (or copy and paste the whole thing) yet or you'll get a file with three broken lines in it. Instead, edit that .py file (with whatever; python comes with IDLE, that's what I used) by replacing the corresponding red lines with the green ones.

(...or just skip all that and use mine!) 
[myfreecams.zip](https://github.com/user-attachments/files/16698862/myfreecams.zip)

**Comment by MartinR577** [comment]
Thanks that did solve it.  It must have pulled the old branch when I did it before. This time I was able to edit the file in the docker container,  restart and it's back online.  thanks all
