### ISSUE TITLE
ManyVids Live support

### ISSUE THREAD

**Issue by yayayeet69** [lossless1024/StreaMonitor#16]
Is there any chance [MV Live](https://www.manyvids.com/mv-live) could be added as a supported site? 

I understand maintenance of existing sites and other potential features are likely more important, but I thought I would ask anyway.

Thanks

**Comment by lossless1024** [comment]
It is possible, but hard, because status polling can only be done with websockets.

**Comment by lossless1024** [comment]
I added it. I also had to implement a new downloader because there are tokens which have to be updated periodically while downloading. FFMpeg doesn't support this.
