### ISSUE TITLE
Mysterious crash happens after a bit.

### ISSUE THREAD

**Issue by xAstroBoy** [lossless1024/StreaMonitor#17]
There's a crash happening during recording streams and the script closes by itself.

**Comment by lossless1024** [comment]
Please send some screenshots or logs

**Comment by xAstroBoy** [comment]
Assertion failed: pfd.revents & POLLIN (C:\projects\libzmq\src\signaler.cpp:265)
Assertion failed: pfd.revents & POLLIN (C:\projects\libzmq\src\signaler.cpp:265)
Assertion failed: pfd.revents & POLLIN (C:\projects\libzmq\src\signaler.cpp:265)

After those, it crashed.

**Comment by xAstroBoy** [comment]
> Please send some screenshots or logs

it happens randomly

**Comment by xAstroBoy** [comment]
@lossless1024 ,it crashes on same error

**Comment by lossless1024** [comment]
One process is running at me for days now. I cannot reproduce it. Try to update the dependencies first with `pip3 install --upgrade -r requirements.txt`

**Comment by lossless1024** [comment]
Did you try it?

**Comment by lossless1024** [comment]
In what kind of environment do you run the program? I mean OS, python version, package versions, etc.

**Comment by xAstroBoy** [comment]
> In what kind of environment do you run the program? I mean OS, python version, package versions, etc.

win11 
![image](https://user-images.githubusercontent.com/92211398/196527787-8685a4c9-8915-46aa-bc09-df600653a141.png)
and Python 3.10.5

**Comment by lossless1024** [comment]
I see. Windows support is untested. There are some users who are successfully running it on windows. Or at least they don't have this issue.
As I see something happens with the ZMQ. Does the crash happen even when you don't use Controller? And do you roam between wireless networks when the crash happens?

**Comment by xAstroBoy** [comment]
> I see. Windows support is untested. There are some users who are successfully running it on windows. Or at least they don't have this issue. As I see something happens with the ZMQ. Does the crash happen even when you don't use Controller? And do you roam between wireless networks when the crash happens?

I don't use the controller file, i always use the downloader and my pc is ethernet, i don't move it anywhere.

**Comment by lossless1024** [comment]
That's weird. Then WSL or native?

**Comment by xAstroBoy** [comment]
> That's weird. Then WSL or native?

wdym?

**Comment by lossless1024** [comment]
Do you run this program in WSL or with python.exe?

**Comment by xAstroBoy** [comment]
> Do you run this program in WSL or with python.exe?

i believe with python.exe

**Comment by lossless1024** [comment]
You might remove lines 15-18 from Downloader.py if you don't use ZMQ. It should avoid the problem.
