### ISSUE TITLE
any sample config.json available ? 

### ISSUE THREAD

**Issue by gumush** [lossless1024/StreaMonitor#19]
Which keys needed ? room_id ? running ? username ? site ( long or 2letter ) ?

**Comment by DerBunteBall** [comment]
Hi,

The config.json structure is as follows:

```
[
   {
       "site": "Chaturbate",
       "username": "some_model",
       "running": true
   },
  {
     ... as above
  }
]
```

You can also use the command line to add stuff.

e.g. start Downloader.py and use Controller.py

```
python3 Controller.py add some_model chaturbate
```

Best Regards

**Comment by lossless1024** [comment]
I think you now have the answer. Thanks @DerBunteBall
