### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by antisad0** [lossless1024/StreaMonitor#2]
when i try to use Controller.py, nothing happens.

**Comment by lossless1024** [comment]
It is not mentioned, but it might not work under Windows. I tested it on Linux and it works for me.
I am planning to do some rework on the manager part to make it more comfortable to use. Also I want to continue implementing the web based manager soon.
In the meantime you can use the same commands in the console when you start Downloader.py

**Comment by antisad0** [comment]
i tested in linux too but not working for me. am i doing something wrong? i installed requirements correctly

**Comment by antisad0** [comment]
oh so i can run commands in Downloader.py, i tested now and worked. you should mention that on readme

**Comment by lossless1024** [comment]
I extended the readme. Also, do you get any error messages, or just it does not work? The controller uses ZeroMQ over TCP, so if have some service listening on port 6969 or have a restrictive firewall, it may not work.

**Comment by antisad0** [comment]
it works now. i think i was running it wrong way

**Comment by lossless1024** [comment]
Ok, then I close the issue
