### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by maddi4u** [lossless1024/StreaMonitor#21]
![image](https://user-images.githubusercontent.com/116060938/196361631-2868789e-3179-4473-808c-17a22222e047.png)

Running windows 10 32 bit
Installed ffmpeg 4.2.2 win32-static
Had installed python 3.10.8 and the same above issue occurred, then uninstalled it and installed python 3.9 but no luck, same issue

**Comment by DerBunteBall** [comment]
Hi,

Can you call ffmpeg from the PowerShell/CMD (not directly)? So open PowerShell or CMD and type ```ffmpeg --help```

Looks like the PATH variable are not correct in that sense that ffmpeg isn't included. If the above gives not found you have the problem identified.

Best Regards

**Comment by maddi4u** [comment]
Thanks for the suggestion
It came like this
![image](https://user-images.githubusercontent.com/116060938/196408893-d50e7fbd-0bb0-4cd0-9eac-16567c8c904f.png)

**Comment by maddi4u** [comment]
What should I do now

**Comment by DerBunteBall** [comment]
You need to add the installation path of FFmpeg to your PATH variable.

e.g. ffmpeg is installed (the binary is placed here) in C:\ffmpeg\bin\ you need to add this to your path. Check this: https://www.h3xed.com/windows/how-to-add-to-and-edit-windows-path-variable

When this is done restart Downloader.py. So close Python completely and re run it. Now it should find ffmpeg. Before doing so you can test the thing by closing CMD/PowerShell reopen one and run ```ffmpeg --help```
 again.
Best Reagrds

**Comment by maddi4u** [comment]
I also renamed the folder and kept it only ffmpeg

**Comment by DerBunteBall** [comment]
Yes. Tried to find your download to verify. Normally it's shipped in a herachical dir structure.

Should work now I think.

Best Regards

**Comment by maddi4u** [comment]
Thankyou so much
Its downloading

**Comment by maddi4u** [comment]
The quality is not good though
It is coming as if it is recording at one frame per two second
Is something wrong

**Comment by DerBunteBall** [comment]
How good ffmpeg performes depends on your internet connection. A normal stream gives something like 800kb/s to 1,5mb/s download average.

**Comment by maddi4u** [comment]
I am using hotspot vpn which is giving 300kb/s
I guess it will be good

**Comment by maddi4u** [comment]
Anyways, doesn't the path get added automatically

**Comment by maddi4u** [comment]
Btw you are the one who made recordurbate, by any chance do you and lossless know each other

**Comment by DerBunteBall** [comment]
300kb/s should be enough but only for one recording I think. It's a bandwidth killer in general.

The path isn't updated in the code. FFmpy which is used as dependency checks the path or takes a executable path. Due to the fact that these path isn't set it checks the path.

I'm not the one who created Recordurbate. Check this repo https://github.com/oliverjrose99/Recordurbate/

Best Regards
