### ISSUE TITLE
Video playing and quality

### ISSUE THREAD

**Issue by maddi4u** [lossless1024/StreaMonitor#24]
When I open the recorded video with the 
1.Default windows 10 films and photo viewer it doesn't play good stops at frames, cubical blurs and out of sync audio and video
2.Google chrome it does not show cubical blur but same stopping at frames and out of sync audio and video

I tried a lot of players(even pot player did same as windows film and photo viewer) and found that the videos play the best in acv video converter no stopping frames, no blurs, no out of sync audio and video(did it get synced automatically) but it did lose or may be skip a very few frames though.

What is happening please tell

**Comment by lossless1024** [comment]
Maybe you have slow connection and some parts don't get downloaded. The site would reduce bandwidth, but this program always try to download the best version. You have already opened another issue for this
