### ISSUE TITLE
VR Stripchat Websocket closes.

### ISSUE THREAD

**Issue by xAstroBoy** [lossless1024/StreaMonitor#25]
There's a possible API update by stripchat on their websocket system .
it keeps closing now.

**Comment by lossless1024** [comment]
Good for me

**Comment by xAstroBoy** [comment]
> 

my console is flooded with websocket connection closed

**Comment by lossless1024** [comment]
It is just a note for debug, you can ignore it if the stream is correctly downloaded

**Comment by lossless1024** [comment]
Maybe that's the problem. Don't play the file while being downloaded. Watch it on the site.

**Comment by xAstroBoy** [comment]
> Maybe that's the problem. Don't play the file while being downloaded. Watch it on the site.

it was smooth before, something must be wrong with either the site, or the model's stream

**Comment by lossless1024** [comment]
I don't experience this. I think the problem is not in the program.

**Comment by mK33y** [comment]
after the updated version I downloaded today sc downloads just looks like this on windows. folder gets created but not getting recorded.
this is gettings spammed in the terminal. 

![Screenshot_16](https://user-images.githubusercontent.com/56261048/197035384-d89cd5bf-9b62-4244-8219-52a6239105a5.png)

cb is working for me on windows.

**Comment by lossless1024** [comment]
@mK33y This is unrelated to this issue. Open new issue next time
However something has definitely changed on the site
