### ISSUE TITLE
UserAgent flag missing in FFmpeg parameters

### ISSUE THREAD

**Issue by Odogwu3000** [lossless1024/StreaMonitor#27]
I noticed UserAgent parameter was left out in FFmpeg function. My SC recordings got broken and after supplying the UA parameter, it got working again.

**Comment by lossless1024** [comment]
It's already fixed in the latest commit.
But I think the SC guys also know this and they're changed a bit on the streaming service again. I'm afraid

**Comment by Odogwu3000** [comment]
Thanks a lot!
