### ISSUE TITLE
MFC away state errors

### ISSUE THREAD

**Issue by rydiy** [lossless1024/StreaMonitor#31]
Streamers on MFC can enter an away state where their account stays logged in and present in the chatroom, but the video broadcast is temporarily disabled.

StreaMonitor seems unprepared for this user state, throwing tons of errors and spamming traceroutes to the console every few seconds.

I'm not sure if this always happens or only under certain circumstances (I've only been using StreaMonitor for a day or two) but there probably ought to be a more elegant way to handle this fairly common occurrence.

**Comment by lossless1024** [comment]
I haven't seen this state before. If you encounter this, please go to https://share.myfreecams.com/<streamer> and save the page source and send it to me somehow. Then I can do something with it.

**Comment by rydiy** [comment]
If you want to try to reproduce it yourself, users who are away get a little tag on their thumbnail just like "Club Show" or "TruePrivate". I don't see any at the moment, but I've attached a screenshot I found on some blog.

![away](https://user-images.githubusercontent.com/116987905/199132950-d5b81657-e059-4a86-a232-44e9e3962249.jpg)

I'll keep an eye out for an active instance to hopefully provide some more useful context, but here's a paste of the last time I observed the error just after I opened this issue:

`2022-10-29 21:42:01,144 - INFO - manager_cli: Unknown command
> stop 2022-10-29 21:42:02,772 - INFO - [MFC] FitKira: Channel online
2022-10-29 21:42:02,772 - INFO - [MFC] FitKira: Started downloading show
FException in thread Thread-415:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/***/***/***/StreaMonitor/StreaMonitor-master/streamonitor/downloaders/ffmpeg.py", line 15, in execute
    ff.run(stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/Users/***/Library/Python/3.9/lib/python/site-packages/ffmpy.py", line 106, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -user_agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0" -c:a copy -c:v copy "downloads/FitKira [MFC]/FitKira-20221029-214203.mp4"` exited with status 1

STDOUT:


STDERR:`
