### ISSUE TITLE
Downloader.py stops searching for online streams

### ISSUE THREAD

**Issue by sminato27** [lossless1024/StreaMonitor#33]
Dunno wtf happens but sometimes it stop searching for online streams. It only get back working when a command is entered.

![image](https://user-images.githubusercontent.com/59450675/198879372-8f278447-1623-4aba-b63f-c11ccfe7a658.png)

**Comment by lossless1024** [comment]
On windows the terminal suspends the running program when you click in it. It restarts when you press enter, too.
