### ISSUE TITLE
Accidentally stopped videos

### ISSUE THREAD

**Issue by sunriceStream** [lossless1024/StreaMonitor#35]
The software works pretty good.
But I stopped accidentally the downloader and some recordings was left, which i can't open with vlc. Can I somehow repair the stream with a ffmpeg command?

**Comment by DerBunteBall** [comment]
In bad case the ffmpeg workers stopped hard.

You could check the files with mediainfo (https://en.wikipedia.org/wiki/MediaInfo).

They present like having no real header when ffmpeg got stopped hard.

Then you only can try one of the dozens of repair tools. Eventually a copy move with ffmpeg tries to fix the file also.

Best Regards

**Comment by sunriceStream** [comment]
i could repair it with https://github.com/anthwlock/untrunc in a Docker-Container - works well!

**Comment by DerBunteBall** [comment]
@sunriceStream: Thanks for the hint. 

This could help people who are in trouble with the stopping problem actually (see #12 ). So working similiar videos could help that tool to figure out the lost media information for corrupted videos also.

Best Regards

**Comment by lossless1024** [comment]
In the latest commits I've improved exit behavior.

**Comment by eldepor** [comment]
> In the latest commits I've improved exit behavior.

I can confirm it's totally fixed now in windows too with the last commit

**Comment by DerBunteBall** [comment]
This can still be helpful.

If a video of a model is corrupted take a working one from the same model and run untrunc on them. It could be fixed if you have luck (the chance is good in such a situation). So still helpful e.g. for a energy loss or some other situation where ffmpeg kills uncontroled.

Best Regards
