### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nsa5574** [lossless1024/StreaMonitor#47]
do I have to open anything so it can record like the downloader.py file, should it be open to record the streams?

**Comment by DerBunteBall** [comment]
You need to start Downloader.py in a PowerShell and keep this PowerShell opened.

You also need to have ffmpeg installed and available in your OS path.

**Comment by nsa5574** [comment]
Another thing I did as you said and checked if it works it didn't record by it self, when opening in powershell do I have to use the command start *?

**Comment by DerBunteBall** [comment]
When you have models in your list they should be shown with the status command.

You need the start/stop command if a model is in the state "Not running" or you want to bring it to that state. "Not running" means the thread is stopped. Normally this isn't the case. So you should see the model name, online status and whether it's recording with the status command.

Make sure that in your PowerShell ```ffmpeg -version``` gives you output.
