### ISSUE TITLE
Downloader.py stopped searching for online streams

### ISSUE THREAD

**Issue by sminato27** [lossless1024/StreaMonitor#5]
It stopped searching for online streams after 18h and only got back working after I pressed a random button on keyboard, why this happened? 

![image](https://user-images.githubusercontent.com/59450675/190539452-7da2737a-1d38-4720-8345-023d2aa93e2f.png)

**Comment by lossless1024** [comment]
I honestly don't know. I haven't tried this program on Windows yet, maybe there is some difference. On which line was it waiting?

**Comment by sminato27** [comment]
Line "2022-09-15 18:51:41,009 - INFO - [CB] lisalaus: No stream" 
Then it got back working when I pressed any random button after 4 hours. Dunno why this happened but now it's working over 3 days without this issue.
