### ISSUE TITLE
FFMpeg executable not found!

### ISSUE THREAD

**Issue by RomanLelek1** [lossless1024/StreaMonitor#57]
Hi there! How do I navigate script to ffmpg executable? I cannot find any file where I can handwrite direction to said file thus Monitor is not working. 
Would aprecciate help

**Comment by DerBunteBall** [comment]
Make sure ffmpeg's directory is in PATH variable. The code searches it in the PATH directories.

Make sure on new bash (Linux) or PowerShell (Windows) ```ffmpeg -version``` works.

**Comment by RomanLelek1** [comment]
Thanks, that worked! I haven't add the ffmpeg to PATH
