### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by TeslaLyon** [lossless1024/StreaMonitor#59]
run: python Downloader.py

log:
Traceback (most recent call last):
  File "/Users/liangshuo/code/py-project/StreaMonitor/Downloader.py", line 9, in <module>
    import streamonitor.sites  # must have
  File "/Users/liangshuo/code/py-project/StreaMonitor/streamonitor/sites/__init__.py", line 7, in <module>
    from . import *
AttributeError: partially initialized module 'streamonitor.sites' has no attribute '' (most likely due to a circular import)

**Comment by DerBunteBall** [comment]
Which Python version do you use?

Tested codebase on 3.11.1 in fresh Python Environment which works.

You could try to comment out line 7 in ```__init__.py``` in ```./streamonitor/sites/``` Folder. 

I think the 
```python 
from . import *
``` 

is interpreted as a self import of the package. This can be a problem of the Python version or the interpreter configuration. Normally the init file already leads to the import.

The best way is using a Python environment. Checkout pyenv with Homebrew. Make sure to have Xcode Command Line Tools installed to have Xcode SDK.

**Comment by TeslaLyon** [comment]
> 

Thanks for the reply, I created a new folder and re-pulled the code, the result is normal operation, I still don't know what caused the problem.

**Comment by DerBunteBall** [comment]
Eventually incompatible cache files after a python version update (more something like 3.8 to 3.10 or so). Also corrupted cache files could lead to strange effects. Eventually a cleanup of them helps.

Cache files are located in ```__pycache__``` folder and have .pyc extension. They contain the [byte code](https://en.wikipedia.org/wiki/Bytecode). Very simple: They are used to run to make things faster. Also look [here](https://stackoverflow.com/questions/2998215/if-python-is-interpreted-what-are-pyc-files).
