### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by gap72** [lossless1024/StreaMonitor#68]
As a total beginner I am trying to start/configure StreaMonitor from the WIndows (8.1) command prompt, but I get the following errors:

![2023-04-06 at 02-13-20](https://user-images.githubusercontent.com/129685709/230241381-c231907b-9e9d-4012-b803-26e8c4e4cfb9.png)

Any idea on why this is happening? I hope I have installed all the required software and set up all the paths correctly. Python version: 3.11.3; FFmpeg version: 2023-04-03-git-6941788d24

**Comment by DerBunteBall** [comment]
You need to install the requirements with pip.

E.g.

```
pip install -r requirements.txt
```

I'm not that fimiliar with Windows "normal" Python installs. You could get conflicts with UAC. So everntually you need to install the requirements for the user. Check ```--user``` option of pip.

**Comment by gap72** [comment]
Thank you for the feedback!

I think I have made some progress. As suggested I have installed the requirements and I have updated pip as well, but I got a deprecation and a warning message, and the script still failed to add a cam for download (sorry for the big attachment).

![2023-04-06 at 03-53-44](https://user-images.githubusercontent.com/129685709/230254129-58927d4f-132d-407b-943f-a93d50fb2b11.png)

**Comment by gap72** [comment]
Doh, silly me for not reading more carefully the readme, the site names in proper format together with abbreviations are listed there. Now everything seems to work just fine, thank you very much for your valuable assistance, without your help I would have never got this script to work. It makes me wanting to learn more abouy python.
