### ISSUE TITLE
Command in docker doesn't work

### ISSUE THREAD

**Issue by johnwig** [lossless1024/StreaMonitor#79]
I run StreaMonitor with docker using command
```docker-compose up```

But no command is working in it

![Screenshot_20230509-001413_Termux](https://user-images.githubusercontent.com/50834078/236875618-624724be-bed8-4e94-99e6-bc9afd5b768e.png)

You can see I tried command `status` with no result.

**Comment by DerBunteBall** [comment]
CLI is disabled in Docker.

Make sure the ZeroMQ Port is exposed to localhost and use Controller.py to control it.

**Comment by johnwig** [comment]
Oh so that is what port 6969 is for in docker-compose.yml.

Would be great if we can configure the port. 6969 is already being used in my system. Had to edit Controller.py to another port to make it working.

**Comment by DerBunteBall** [comment]
Downlaoder.py as well as Controller.py are not really configurable actually that's true.

You could also workaround this by creating a one time running Docker Container for Controller.py and create a bash wrapper to start it up for commands. The Containers could have there own network.
