### ISSUE TITLE
Camsoda recording does not work, but other websites do

### ISSUE THREAD

**Issue by yayayeet69** [lossless1024/StreaMonitor#8]
When I run the script for CamSoda, the video file is created but never increases in size past 256 KB.

![Screenshot_20221001_234256](https://user-images.githubusercontent.com/90543997/193412738-c6f9258d-69db-4a16-a21c-92b69912a1e9.png)

![Screenshot_20221001_234312](https://user-images.githubusercontent.com/90543997/193412740-2167d8a2-8603-4f19-a935-29ec73125b03.png)

- I have tried running it for MFC and it works as expected.
- I am running Python 3.10 on EndeavourOS (Linux).
- I have tried changing the user agent in the CamSoda.py file to a generic Google Chrome Windows 10 PC

**Comment by lossless1024** [comment]
Thank you, it really is a bug. I'll check it ASAP
