### ISSUE TITLE
Running code online (cloud/server)

### ISSUE THREAD

**Issue by maddi4u** [lossless1024/StreaMonitor#83]
Hello,
        How do i run this script on cloud or online server as i cant keep my pc running 24x7.
I tried pythonanywhere but it didn't work. It did not give any output after add model command, it was just blank. I did install all requirements correctly. After a little while I coudn't even start downloader.py , it gave error - port 5000 already in use, close the already running program or open a new one.

Sorry if I am little off topic, I don't know any other way.
Please help. I am new to this.

**Comment by DerBunteBall** [comment]
Like this:

1. Rent a dedictaed server or cloud instance
2. Install Linux/BSD on it. Providers make this possible via panal
3. Setup Python in a way you like it.
4. Install ffmpeg (included in all distros)
5. Alternatively setup Docker CE, build container and run it.
6. Setup Firewall e.g. with UFW and make your SSH server save (e.g. public key auth and so on).

All done.

**Comment by maddi4u** [comment]
Thankyou.
