### ISSUE TITLE
Amateur TV

### ISSUE THREAD

**Issue by webmastermario** [lossless1024/StreaMonitor#93]
it seesm amateur.tv the new plugin has additional token security. does anyone know how to correct this?

**Comment by DerBunteBall** [comment]
I can not verify this.

API request still works. Which error do you get?

**Comment by webmastermario** [comment]
i tried with ffmpeg directly and receive this:  Server returned 401 Unauthorized (authorization failed). When i access the URL in my broswer (the mp4 or m3u8 url) it is working..

**Comment by DerBunteBall** [comment]
Try to send a Referrer Header with https://amateur.tv/ as value.

Check -headers option in ffmpeg.

**Comment by webmastermario** [comment]
get this 
No trailing CRLF found in HTTP header. Adding it.  and than  Server returned 401 Unauthorized. have this added to the ffmpeg command: -headers "Referer: https://amateur.tv"

**Comment by webmastermario** [comment]
was able to get streams by adding: -user_agent 

thanks for helping.

**Comment by DerBunteBall** [comment]
That's a second header.

Always when calling APIs like that or streaming servers always add a "User-Agent" Header. They block nearly all when they don't see something like a Firefox or so.

I assumed that this already was done.

Have a nice day.
