### ISSUE TITLE
Cherry TV not working

### ISSUE THREAD

**Issue by webmastermario** [lossless1024/StreaMonitor#96]
hello, 

anybody know if cherry tv still works. I have tested it in the browser and pull URL shows as "null" so no stream input. Does someone know how to get the correct URL?

Thanks

**Comment by webmastermario** [comment]
for some models it shows the m3u8 url. why is that?

**Comment by DerBunteBall** [comment]
Looks bad.

Seems they changed much.

**Comment by webmastermario** [comment]
you think there is a workaround to get this to work?
