### ISSUE TITLE
Issue with Stripchat recordings

### ISSUE THREAD

**Issue by trcishere** [lossless1024/StreaMonitor#97]
I'm seeing issues recording from Stripchat, specifically, videos are shorter than they should be and sometimes freeze. Here are a few sample error logs that I see when I turn DEBUG=true. Anyone seeings something similar or have any suggestions? 

[sample1.stderr.log](https://github.com/lossless1024/StreaMonitor/files/12180648/Liz_and_Pit-20230727-001142.mp4.stderr.log)
[sample2.stderr.log](https://github.com/lossless1024/StreaMonitor/files/12180636/Liz_and_Pit-20230727-061149.mp4.stderr.log)

**Comment by gh0stwolf** [comment]
Having a similar issue only with [sc] the video stutters/freezes frequently through the entire video. [cb] doesnt have this issue with resolution maxed out. I tried running locally with similar issue. Running in docker container using sc.global mirror.

**Comment by happyfox-dot** [comment]
![image](https://github.com/lossless1024/StreaMonitor/assets/58945940/f5a6e3c9-b30f-44ab-b65b-d970e8c2bcee)
from the log, may be there is a network errror.
